server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/study
        username: root
        password: 111111
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
          max-active: 20
          initial-size: 1
          max-wait: 60000
          min-idle: 1
          minEvictableIdleTimeMillis: 300000
          timeBetweenEvictionRunsMillis: 60000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          filters: stat
    activiti:
        check-process-definitions: true #自动检查、部署流程定义文件
        database-schema-update: true #自动更新数据库结构
        process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
logging:
  level.org.activiti.engine.impl.persistence.entity: debug
